### PR TITLE
Add global sensitive props scripts

### PR DESCRIPTION
**Pull request by osm0sis**
Needed for SafetyNet/Play Integrity and numerous root detection systems/apps

### CODE REVIEW

**Comment by snake-4** [comment]
Looks good. Thanks for the PR!

**Comment by osm0sis** [comment]
Sorry, I missed something. Care to unmerge, and i'll fix up?

**Comment by osm0sis** [comment]
Oh, even worse. Why don't you force push back to the previous state so we get rid of all this mess and I'll try again.

**Comment by snake-4** [comment]
Done

**Comment by osm0sis** [comment]
Sorry about all that! Bad timing, I was literally just coming here to mark Draft and fix up. 😓

**Comment by snake-4** [comment]
Is it the lack of waiting for `sys.boot_completed`?

**Comment by osm0sis** [comment]
Yeah, exactly. I had already updated my scripts to use resetprop -w instead but that requires newest Magisk Canary, so I was undoing that part for the PR here and missed that.

**Comment by osm0sis** [comment]
Fixed for #57

**Pull request merged**
